name: Cooking Kernel
on: push
jobs:
  build:
    name: Building
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Build
      run: |
      
      # Install dependencies
        ubuntu_codename=`lsb_release -c | cut -f2`
        wget https://apt.llvm.org/llvm-snapshot.gpg.key
        sudo apt-key add llvm-snapshot.gpg.key
        sudo add-apt-repository "deb http://apt.llvm.org/$ubuntu_codename/ llvm-toolchain-$ubuntu_codename main"
        sudo apt-get update && sudo apt-get install -y clang llvm lld binutils-aarch64-linux-gnu gcc-aarch64-linux-gnu binutils-arm-linux-gnueabi \
        gcc-arm-linux-gnueabi libncurses-dev flex bison openssl libssl-dev dkms libelf-dev libudev-dev libpci-dev libiberty-dev autoconf ccache
        sudo ln -sf /usr/bin/ccache /usr/local/bin/clang
        ccache -M 4.5
     
     # Set Time Zone
         TZ=Asia/Jakarta
         sudo ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone && \
         sudo apt-get install -y install tzdata
         
     # Clone source and build
         git clone --quiet -j64 --depth=1 https://github.com/greenforce-project/kernel_xiaomi_citrus_sm6115 -b main kernel
         cd kernel && wget https://github.com/timangpopi1/github_run/raw/main/build.sh
         export codename="juice" && export defconfig="vendor/juice-perf_defconfig"
         chmod +x build.sh && bash ./build.sh $defconfig "GreenForce" "POCO M3 & Redmi 9T"
