name: Cooking Kernel
on: push
jobs:
  build:
    name: Building
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Build
      run: |
        ubuntu_codename=`lsb_release -c | cut -f2`
        wget https://apt.llvm.org/llvm-snapshot.gpg.key
        sudo apt-key add llvm-snapshot.gpg.key
        sudo add-apt-repository "deb http://apt.llvm.org/$ubuntu_codename/ llvm-toolchain-$ubuntu_codename main"
        sudo apt-get update && sudo apt-get install -y clang llvm lld binutils-aarch64-linux-gnu gcc-aarch64-linux-gnu binutils-arm-linux-gnueabi \
        gcc-arm-linux-gnueabi libncurses-dev flex bison openssl libssl-dev dkms libelf-dev libudev-dev libpci-dev libiberty-dev autoconf ccache
        sudo ln -sf /usr/bin/ccache /usr/local/bin/clang
        ccache -M 4.5
